name: Godwoken Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  godwoken-tests:
    uses: nervosnetwork/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@develop
    with:
      extra_github_env: |
        MANUAL_BUILD_WEB3=true
        MANUAL_BUILD_WEB3_INDEXER=true
        WEB3_GIT_URL=https://github.com/${{ github.repository }}
        WEB3_GIT_CHECKOUT=${{ github.ref }}
        GODWOKEN_TESTS_REF=refs/pull/163/head
        GODWOKEN_PREBUILD_IMAGE_NAME=ghcr.io/nervosnetwork/godwoken-prebuilds:1.4.2-rc2-202207211420
